services:

  postgres:
    image: timescale/timescaledb-ha:pg18
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d main"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: main

  flyway:
    image: flyway/flyway:12.0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations/sql:/flyway/sql:ro
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/main
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_LOCATIONS: filesystem:/flyway/sql